name: currency_fractal
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  path: ^1.8.0
  web3dart: ^2.5.1
  frac:
    path: ../frac
  fractals:
    path: ../fractals
  dio: ^4.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
