name: currency_fractal
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path: ^1.8.0
  webthree: ^2.5.8
  frac:
    path: ../frac
  fractal:
    path: ../fractal
  fractal_base:
    path: ../fractal_base
  signed_fractal:
    path: ../signed_fractal

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
