name: currency_fractal
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  path: ^1.8.0
  crypto_fractal:
    path: ../crypto_fractal
  fractal:
    path: ../fractal
  webthree: ^2.7.5

dev_dependencies:
  lints: ^4.0.0
